OnlineOrder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from OnlineOrder import settings

urlpatterns = [
    url(r'^shopmgr/', include('shopmgr.urls')),
    url(r'^mainpage/', include('mainpage.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^authorize$', views.authorize, name='authorize'),
    url(r'^jmp_register$', views.jmp_to_register, name='jmp_to_register'),
    url(r'^register_page$', views.register_page, name='register_page'),
    url(r'^registered$', views.register, name='register'),
    url(
        r'duplicated_username',
        views.handle_duplicate,
        name="duplicated_username"),
    url(r'^log_out$', views.log_out, name='log_out'),
]

mainpage/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainpage'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^complete_info$', views.complete_info, name='complete'),
    url(r'^location$', views.location, name='location'),
    url(r'^personal_center$', views.jmp_to_personal, name='personal_center'),
    url(r'^jmp_to_complete_info$', views.jmp_to_complete_info,
        name="jmp_to_complete_info"),
    url(r'^query_user_info$', views.query_user_info, name="query_user_info"),
    url(r'^check_origin_pwd$', views.check_origin_pwd, name="check_origin_pwd"),
    url(r'^change_password$', views.change_password, name="change_password"),
    url(r'^add_addr$', views.add_address, name="add_addr"),
    url(r'^get_address_count$', views.get_address_count,
        name="get_address_count"),
    url(r'^show_first_page$', views.show_first_page, name="show_first_page"),
    url(r'^del_addr$', views.del_addr, name="del_addr"),
    url(r'^conf_default_addr$', views.conf_default_addr,
        name="conf_default_addr"),
    url(r'^(?P<shop_id>[0-9]+)/jmp_to_shop_detail/$',
        views.jmp_to_shop_detail, name='jmp_to_shop_detail'),
    url(r'^(?P<shop_id>[0-9]+)/shop_detail/$',
        views.shop_detail, name='shop_detail'),
    url(r'^shoppingcar$', views.jmp_to_shoppingcar, name='shoppingcar'),
    url(r'^show_shops_orderby_sales$', views.show_shops_orderby_sales,
        name='show_shops_orderby_sales'),
    url(r'^get_merchandises$', views.get_merchandises,
        name="get_merchandises"),
    url(r'^get_spec_shopinfo$', views.get_spec_shopinfo,
        name="get_spec_shopinfo"),
    url(r'^get_my_threemonth_order$', views.get_my_threemonth_order,
        name='get_my_threemonth_order'),
    url(r'^add_to_shopcar$', views.add_to_shopcar, name='add_to_shopcar'),
    url(r'^get_cart$', views.get_cart, name='get_cart'),
    url(r'^flush_cart$', views.flush_cart, name='flush_cart'),
    url(r'^get_shop_by_keywords$', views.get_shop_by_keywords,
        name="get_shop_by_keywords"),
    url(r'^get_shopinfo_by_id$', views.get_shopinfo_by_id,
        name="get_shopinfo_by_id"),
    url(r'^get_merchan_by_id$', views.get_merchan_by_id,
        name="get_merchan_by_id"),
    url(r'^place_order$', views.place_order, name="place_order"),
    url(r'^register_shop$', views.register_shop, name='register_shop'),
    url(r'^confirm_order$', views.confirm_order, name="confirm_order"),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^cancel_spec_order$', views.cancel_sepc_order, name='cancel_spec_order'),
    url(r'^delete_food_from_order$', views.delete_food_from_order, name='delete_food_from_order'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserMgr(BaseUserManager):
    def create_user(self, username, password):
        user = self.model(username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        email = self.normalize_email(email)
        user = self.model(username=username, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    objects = UserMgr()
    username = models.CharField(max_length=20, unique=True)
    email = models.CharField(max_length=50)
    cellphone = models.CharField(max_length=15)
    USERNAME_FIELD = 'username'  # declare that username to be unique
    is_active = models.BooleanField(default=True)
    is_shop = models.BooleanField(default=False)

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    class Meta:
        db_table = 'User'

login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    return render(request, 'login/index.html')


def authorize(request):
    user_name = request.POST['user_name']
    password = request.POST['user_pwd']
    user = authenticate(username=user_name, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('mainpage:index'))
    else:
        return render(request, 'login/index.html', {
            'error_message': 'non-existed user or wrong password',
        })


def log_out(request):
    logout(request)
    return render(request, 'mainpage/index.html')


def jmp_to_register(request):
    return HttpResponseRedirect(reverse('login:register_page'))


def register_page(request):
    return render(request, 'login/register_page.html')


def register(request):
    name = request.POST['user_name']
    password = request.POST['user_pwd']
    try:
        user = User.objects.create_user(name, password)
        user.save()
    except:
        return HttpResponse(2)
    user = authenticate(username=name, password=password)
    login(request, user)
    return HttpResponse(1)


def handle_duplicate(request):
    user_name = request.POST['name']
    try:
        user = User.objects.get(username=user_name)
        return HttpResponse(0)
    except User.DoesNotExist:
        return HttpResponse(1)

login/templates/login/index.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <title>Login</title>
    <link href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'login/css/mystyle.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'login/jquery-3.2.1.js' %}"></script>
</head>

<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <a href="{% url 'mainpage:index' %}">Online<span>Order</span></a> 
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div class="row">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-9">
            <div class="col-sm-offset-3">
                {% if error_message %}
                <p id="err_msg"><strong>{{ error_message }}</strong></p>{% endif %}
            </div>
            <form class="form-horizontal" action="{% url 'login:authorize' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Username</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" name="user_name" value="" onclick="rm_err_msg()">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-3">
                        <input type="password" class="form-control" name="user_pwd">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-4">
                        <button type="submit" class="btn btn-success">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
    function rm_err_msg() {
        var err_msg = document.getElementById("err_msg");
        if (err_msg) {
            err_msg.parentNode.removeChild(err_msg)
        }
    }
    </script>
</body>

</html>

login/templates/login/register_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Sign up| Online Order</title>
    <!-- Bootstrap -->
    <link href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'login/css/mystyle.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'login/css/register_page.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'login/jquery-3.2.1.js' %}"></script>
</head>

<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <a href="{% url 'mainpage:index' %}">Online <span>Order</span></a>
            </div>
        </div>
    </div>
    <div class="register_content">
        <form class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <input class="form-control" id="nameFocusedInput" type="text" value="" name="user_name">
                        </div>
                        <label class="col-sm-5 control-label usernameTip">Username already exist!</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Create Password</label>
                <div class="col-sm-10">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <input class="form-control" id="passwordFocusedInput" type="password" value="" name="user_pwd">
                        </div>
                        <label class="col-sm-5 control-label" for="passwordFoucusedInput" hidden></label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Confirm Password</label>
                <div class="col-sm-10">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <input class="form-control" id="ensurePasswordFocusedInput" type="password" value="">
                        </div>
                        <label class="col-sm-5 control-label ensurePasswordTip" for="ensurePasswordFocusedInput">Please confirm your password</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"></label>
                <!-- <div class="col-sm-10"> -->
                    <div class="form-group">
                        <div class="col-sm-8">
                            <button type="button" class="btn btn-success" id="signup_btn">
                                Sign up
                            </button>
                            <button type="button" class="btn btn-success" id="back_mainpage">Back</button>
                        </div>
                    </div>
                <!-- </div> -->
            </div>
        </form>
    </div>
    <!--footer-->
    <div class="myfooter">
        <div class="container">
            <div class="copy">
                <p>Copyright &copy; 2017. ZIYANG WANG &amp; MIAOGAO</p>
            </div>
        </div>
    </div>
    <!--footer-->
    <script>
    $("#signup_btn").click(function() {
        var username = $.trim($("#nameFocusedInput").val());
        var password1 = $.trim($("#passwordFocusedInput").val());
        var password2 = $.trim($("#ensurePasswordFocusedInput").val());
        if (username != "" && password1 != "" && password2 != "" && password1 == password2) {
            $.post("{% url 'login:register' %}", {
                user_name: username,
                user_pwd: password1,
                'csrfmiddlewaretoken': '{{csrf_token}}'
            }, function(data, status) {
                if (data == 1) {
                    //success
                    alert("Sign up successfully");
                    location.href = "{% url 'mainpage:jmp_to_complete_info' %}";
                } else if (data == 2) {
                    //failed
                    alert("Sign up failed");
                }

            });
        } else {
            //something wrong
            alert("Please fill all required fields correctly");
        }
    });

    $('#back_mainpage').click(function(){
        location.href = "{% url 'mainpage:index' %}";
    });

    $("#nameFocusedInput").focusin(function() {
        if ($.trim($(this).val()) != "" && $(".usernameTip").css("visibility") == "visible") {
            $(".usernameTip").css("visibility", "hidden");
        }
    });



    $("#nameFocusedInput").focusout(function() {
        //alert("out");
        var aName = $.trim($("#nameFocusedInput").val());
        if (aName != "") {
            //duplicated name
            $.post("{% url 'login:duplicated_username' %}", {
                name: aName,
                'csrfmiddlewaretoken': '{{csrf_token}}'
            }, function(data, status) {
                if (data == 0) {
                    //existed username
                    $(".usernameTip").css("visibility", "visible");
                }
            });
        }
    });


    $("#ensurePasswordFocusedInput").focusout(function() {
        var password1 = $.trim($("#passwordFocusedInput").val());
        var password2 = $.trim($("#ensurePasswordFocusedInput").val());

        if (password1 != "" && password2 != "" && password2 != password1) {
            $(".ensurePasswordTip").css("visibility", "visible");

        }

    });

    $("#ensurePasswordFocusedInput").focusin(function() {
        if ($.trim($(this).val()) != "" && $(".ensurePasswordTip").css("visibility") == "visible") {
            $(".ensurePasswordTip").css("visibility", "hidden");
        }
    });
    </script>
</body>

</html>