OnlineOrder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from OnlineOrder import settings

urlpatterns = [
    url(r'^shopmgr/', include('shopmgr.urls')),
    url(r'^mainpage/', include('mainpage.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^authorize$', views.authorize, name='authorize'),
    url(r'^jmp_register$', views.jmp_to_register, name='jmp_to_register'),
    url(r'^register_page$', views.register_page, name='register_page'),
    url(r'^registered$', views.register, name='register'),
    url(
        r'duplicated_username',
        views.handle_duplicate,
        name="duplicated_username"),
    url(r'^log_out$', views.log_out, name='log_out'),
]

mainpage/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainpage'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^complete_info$', views.complete_info, name='complete'),
    url(r'^location$', views.location, name='location'),
    url(r'^personal_center$', views.jmp_to_personal, name='personal_center'),
    url(r'^jmp_to_complete_info$', views.jmp_to_complete_info,
        name="jmp_to_complete_info"),
    url(r'^query_user_info$', views.query_user_info, name="query_user_info"),
    url(r'^check_origin_pwd$', views.check_origin_pwd, name="check_origin_pwd"),
    url(r'^change_password$', views.change_password, name="change_password"),
    url(r'^add_addr$', views.add_address, name="add_addr"),
    url(r'^get_address_count$', views.get_address_count,
        name="get_address_count"),
    url(r'^show_first_page$', views.show_first_page, name="show_first_page"),
    url(r'^del_addr$', views.del_addr, name="del_addr"),
    url(r'^conf_default_addr$', views.conf_default_addr,
        name="conf_default_addr"),
    url(r'^(?P<shop_id>[0-9]+)/jmp_to_shop_detail/$',
        views.jmp_to_shop_detail, name='jmp_to_shop_detail'),
    url(r'^(?P<shop_id>[0-9]+)/shop_detail/$',
        views.shop_detail, name='shop_detail'),
    url(r'^shoppingcar$', views.jmp_to_shoppingcar, name='shoppingcar'),
    url(r'^show_shops_orderby_sales$', views.show_shops_orderby_sales,
        name='show_shops_orderby_sales'),
    url(r'^get_merchandises$', views.get_merchandises,
        name="get_merchandises"),
    url(r'^get_spec_shopinfo$', views.get_spec_shopinfo,
        name="get_spec_shopinfo"),
    url(r'^get_my_threemonth_order$', views.get_my_threemonth_order,
        name='get_my_threemonth_order'),
    url(r'^add_to_shopcar$', views.add_to_shopcar, name='add_to_shopcar'),
    url(r'^get_cart$', views.get_cart, name='get_cart'),
    url(r'^flush_cart$', views.flush_cart, name='flush_cart'),
    url(r'^get_shop_by_keywords$', views.get_shop_by_keywords,
        name="get_shop_by_keywords"),
    url(r'^get_shopinfo_by_id$', views.get_shopinfo_by_id,
        name="get_shopinfo_by_id"),
    url(r'^get_merchan_by_id$', views.get_merchan_by_id,
        name="get_merchan_by_id"),
    url(r'^place_order$', views.place_order, name="place_order"),
    url(r'^register_shop$', views.register_shop, name='register_shop'),
    url(r'^confirm_order$', views.confirm_order, name="confirm_order"),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^cancel_spec_order$', views.cancel_sepc_order, name='cancel_spec_order'),
    url(r'^delete_food_from_order$', views.delete_food_from_order, name='delete_food_from_order'),
]

shopmgr/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopmgr'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^show_today_orders_shop$', views.show_today_orders_shop, name='show_today_orders_shop'),
    url(r'^complete_shopinfo$', views.complete_shopinfo, name='complete_shopinfo'),
    url(r'^show_personal_info$', views.show_personal_info, name='show_personal_info'),
    url(r'^add_icon$', views.add_icon, name='add_icon'),
    url(r'^show_incoming_orders$', views.show_incoming_orders, name="show_incoming_orders"),
    url(r'^show_completed_orders$',views.show_completed_orders, name="show_completed_orders"),
    url(r'^add_goods$', views.add_goods, name="add_goods"),
    url(r'^jmp_to_manage_goods$', views.jmp_to_manage_goods, name="jmp_to_manage_goods"),
    url(r'^delete_good$', views.delete_good, name="delete_good"),
    url(r'^confirm_order$', views.confirm_order, name="confirm_order"),
    url(r'^decline_order$', views.decline_order, name="decline_order"),
]

shopmgr/models.py
from django.db import models

# Create your models here.

shopmgr/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from login.models import User
import json
from mainpage.models import Orders, OrderDetail, Address
from mainpage.models import Shop, Merchandise, SalesNum
from datetime import datetime
import decimal


# Create your views here.

def json_serialize(obj):
    if isinstance(obj, datetime):
        serial = obj.isoformat()
        return serial
    raise TypeError('Type not serializable')


def decimal_default(obj):
    if isinstance(obj, decimal.Decimal):
        return float(obj)
    raise TypeError('Type not serializable')


def index(request):
    print("show index")
    shop = Shop.objects.get(user_id_id=request.user.id)
    shop_id = shop.id
    complete_order_count = Orders.objects.filter(shop_id_id=shop_id, status=2).count()
    order_tobe_comfirm_count = Orders.objects.filter(shop_id_id=shop_id, status=0).count()
    print(order_tobe_comfirm_count)
    return render(request, 'shopmgr/index.html',
                  {'user': request.user,
                   'complete_order_count': complete_order_count,
                   'order_tobe_confirm': order_tobe_comfirm_count})


def show_today_orders_shop(request):
    print("show today orders")
    shop = Shop.objects.get(user_id_id=request.user.id)
    shop_id = shop.id
    order_table = Orders.objects.filter(shop_id_id=shop_id, status=1).values()
    order_list = list(order_table)
    for order in order_list:
        addr_id = order['address_id_id']
        addr = Address.objects.get(pk=addr_id)
        order['address_id_id'] = addr.province + addr.city + addr.county + addr.street

    # print(order_list)
    response_data = {}
    print(order_list)
    response_data['orders'] = order_list
    return HttpResponse(json.dumps(response_data, default=json_serialize))


def show_incoming_orders(request):
    shop = Shop.objects.get(user_id_id=request.user.id)
    shop_id = shop.id
    order_table = Orders.objects.filter(shop_id_id=shop_id, status=0).values()
    order_list = list(order_table)
    for order in order_list:
        addr_id = order['address_id_id']
        addr = Address.objects.get(pk=addr_id)
        order['address_id_id'] = addr.province + addr.city + addr.county + addr.street

    response_data = {}
    response_data['orders'] = order_list
    return HttpResponse(json.dumps(response_data, default=json_serialize))


def show_completed_orders(request):
    shop = Shop.objects.get(user_id_id=request.user.id)
    shop_id = shop.id
    order_table = Orders.objects.filter(shop_id_id=shop_id, status=2).values()
    order_list = list(order_table)
    for order in order_list:
        addr_id = order['address_id_id']
        addr = Address.objects.get(pk=addr_id)
        order['address_id_id'] = addr.province + addr.city + addr.county + addr.street

    response_data = {}
    response_data['orders'] = order_list
    return HttpResponse(json.dumps(response_data, default=json_serialize))


def complete_shopinfo(request):
    shop = Shop.objects.get(user_id_id=request.user.id)
    print(shop)
    return render(request, 'shopmgr/complete_shopinfo.html', {'user': request.user, 'shop': shop})


def show_personal_info(request):
    shop = Shop.objects.filter(user_id_id=request.user.id).values()
    shop_info = list(shop)
    response_data = {}
    response_data['shop_info'] = shop_info
    return HttpResponse(json.dumps(response_data, default=decimal_default))


def add_icon(request):
    if request.method == 'POST':
        shop = Shop.objects.get(user_id_id=request.user.id)
        # if request.FILES['icon'] is not None:
        image_file = request.FILES['icon']
        deliver_fee = int(request.POST['deliver_fee'])
        least_price = int(request.POST['least_price'])
        shopname = request.POST['shopname']
        # print(request.POST.items().values())
        try:
            shop.deliver_fee = deliver_fee
            shop.least_price = least_price
            shop.shopname = shopname
            if image_file:
                shop.shop_img = image_file
            shop.save()
            return HttpResponseRedirect(reverse("shopmgr:complete_shopinfo"))
        except:
            return render(request, 'shopmgr/complete_shopinfo.html',
                          {'user': request.user, 'message': 'Uploading failed!'})


def add_goods(request):
    if request.method == 'POST':
        title = request.POST['title']
        price = int(request.POST['price'])
        image_file = request.FILES['icon']
        shop = Shop.objects.get(user_id_id=request.user.id)
        shop_id = shop.id
        try:
            m = Merchandise(title=title, price=price, shop_id_id=shop_id)
            m.image = image_file
            m.save()
            return HttpResponseRedirect(reverse("shopmgr:jmp_to_manage_goods"))
        except:
            return render(request, 'shopmgr/manage_goods.html', {'user': request.user, 'message': 'Uploading failed!'})


def jmp_to_manage_goods(request):
    shop = Shop.objects.get(user_id_id=request.user.id)
    shop_id = shop.id
    m = Merchandise.objects.filter(shop_id_id=shop_id).values()
    goods_list = list(m)
    print(goods_list)
    return render(request, 'shopmgr/manage_goods.html', {'user': request.user, 'goods_list': goods_list})


def delete_good(request):
    good_id = int(request.POST['good_id'])
    try:
        Merchandise.objects.get(pk=good_id).delete()
        return HttpResponse(1)
    except:
        return HttpResponse(0)


def confirm_order(request):
    order_num = request.POST['order_num']
    order = Orders.objects.get(order_num=order_num)
    order.status = 1
    order.save()
    return HttpResponse(1)

def decline_order(request):
    orderNum = request.POST['orderNum']
    try:
        order = Orders.objects.get(order_num=orderNum)
        order.status = 3
        order.save()
        return HttpResponse(1)
    except: 
        return HttpResponse(0)

shopmgr/templates/shopmgr/complete_shopinfo.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Forms - SB Admin</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'shopmgr/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Add custom CSS here -->
    <link href="{% static 'shopmgr/css/sb-admin.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'shopmgr/css/font-awesome.min.css' %}">
    <script src="{% static 'shopmgr/js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'shopmgr/js/bootstrap.js' %}"></script>
    <script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function htmlEntities(str) {
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }
    var csrftoken = getCookie('csrftoken');
    $(document).ready(function() {
        console.log("ready!");
        // showinfo();
        var lis = '<ul><li><h3>Name: ' + "{{shop.shopname}}" + '</h3></li><li><h3>Rating: ' + "{{shop.review_score}}" + '</h3></li><li><img height=150px width=200px src=\"{{MEDIA_URL}}{{shop.shop_img}}\"/></li></ul>';
        $(lis).appendTo("#personal_info");
    });
    </script>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'mainpage:index' %}">Online Order</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active"><a href="{% url 'shopmgr:index' %}"><i class="fa fa-dashboard"></i> Order Center</a></li>
                    <li><a href="{% url 'shopmgr:jmp_to_manage_goods' %}"><i class="fa fa-bar-chart-o"></i> Manage goods</a></li>
                    <li><a href="{% url 'shopmgr:complete_shopinfo' %}"><i class="fa fa-table"></i> Update Info</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right navbar-user">
                    <li class="dropdown messages-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Messages <span class="badge">7</span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">7 New Messages</li>
                        </ul>
                    </li>
                    <li class="dropdown alerts-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alerts <span class="badge">3</span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Default <span class="label label-default">Default</span></a></li>
                            <li><a href="#">Primary <span class="label label-primary">Primary</span></a></li>
                            <li><a href="#">Success <span class="label label-success">Success</span></a></li>
                            <li><a href="#">Info <span class="label label-info">Info</span></a></li>
                            <li><a href="#">Warning <span class="label label-warning">Warning</span></a></li>
                            <li><a href="#">Danger <span class="label label-danger">Danger</span></a></li>
                            <li class="divider"></li>
                            <li><a href="#">View All</a></li>
                        </ul>
                    </li>
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{user.username}} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                            <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'login:log_out' %}"><i class="fa fa-power-off"></i> Log Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Update Information</h1>
                </div>
            </div>
            <!-- /.row -->
            <div class="col-lg-4" id="personal_info">
                <h1>Restaurant</h1>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <form enctype="multipart/form-data" role="form" action="{% url 'shopmgr:add_icon' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Upload your icon</label>
                            <input type="file" name="icon" /> {% if message %}
                            <label>{{message}}</label>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label>Name</label>
                            <input class="form-control" name="shopname" id="shopname">
                        </div>
                        <div class="form-group">
                            <label>Least Price</label>
                            <input class="form-control" name="least_price" id="least_price">
                        </div>
                        <div class="form-group">
                            <label>Deliver Fee</label>
                            <input class="form-control" name="deliver_fee" id="deliver_fee">
                        </div>
                        <button type="submit" class="btn btn-default">Confirm</button>
                        <button type="reset" class="btn btn-default">Reset</button>
                    </form>
                </div>
                <div class="col-lg-6">
                </div>
                <!-- /.row -->
            </div>
            <!-- /#page-wrapper -->
        </div>
    </div>
    <!-- /#wrapper -->
    <!-- JavaScript -->
</body>

</html>

shopmgr/templates/shopmgr/manage_goods.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Forms - SB Admin</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'shopmgr/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Add custom CSS here -->
    <link href="{% static 'shopmgr/css/sb-admin.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'shopmgr/css/font-awesome.min.css' %}">
    <script src="{% static 'shopmgr/js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'shopmgr/js/bootstrap.js' %}"></script>
    <script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function delete_good(good_id) {
        console.log(good_id);
        $.post("/shopmgr/delete_good", {
            csrfmiddlewaretoken: csrftoken,
            good_id: good_id
        }, function(data, status) {
            if (data == 1) {
                location.reload(true);
            } else {
                alert("delete failed");
            }
        });
    }
    $(document).ready(function() {
        console.log("ready!");
        // showinfo();
    });
    </script>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'mainpage:index' %}">Online Order</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active"><a href="{% url 'shopmgr:index' %}"><i class="fa fa-dashboard"></i> Order Center</a></li>
                    <li><a href="{% url 'shopmgr:jmp_to_manage_goods' %}"><i class="fa fa-bar-chart-o"></i> Manage goods</a></li>
                    <li><a href="{% url 'shopmgr:complete_shopinfo' %}"><i class="fa fa-table"></i> Update Info</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right navbar-user">
                    <li class="dropdown messages-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Messages <span class="badge">7</span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">7 New Messages</li>
                        </ul>
                    </li>
                    <li class="dropdown alerts-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alerts <span class="badge">3</span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Default <span class="label label-default">Default</span></a></li>
                            <li><a href="#">Primary <span class="label label-primary">Primary</span></a></li>
                            <li><a href="#">Success <span class="label label-success">Success</span></a></li>
                            <li><a href="#">Info <span class="label label-info">Info</span></a></li>
                            <li><a href="#">Warning <span class="label label-warning">Warning</span></a></li>
                            <li><a href="#">Danger <span class="label label-danger">Danger</span></a></li>
                            <li class="divider"></li>
                            <li><a href="#">View All</a></li>
                        </ul>
                    </li>
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{user.username}} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                            <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'login:log_out' %}"><i class="fa fa-power-off"></i> Log Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        {% if goods_list %}
        <div id="page-wrapper">
            <div class="panel-body">
                <div class="table-responsive" id="goods">
                    <table class="table table-bordered table-hover table-striped tablesorter">
                        <thead>
                            <tr>
                                <th>Food <i class="fa fa-sort"></i></th>
                                <th>Price <i class="fa fa-sort"></i></th>
                                <th>Picture <i class="fa fa-sort"></i></th>
                                <th>Operate <i class="fa fa-sort"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for good in goods_list %}
                            <tr>
                                <th>{{good.title}}</th>
                                <th>{{good.price}}</th>
                                <th><img height=150px width=200px src="{{MEDIA_URL}}{{good.image}}"></th>
                                <th>
                                    <button class="btn btn-default" onclick="delete_good({{good.id}})">Delete</button>
                                </th>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="text-right">
                    <a href="#">View All Transactions <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            {% endif %}
            <div class="row">
                <div class="col-lg-6">
                    <form enctype="multipart/form-data" role="form" action="{% url 'shopmgr:add_goods' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Upload your picture</label>
                            <input type="file" name="icon" /> {% if message %}
                            <label>{{message}}</label>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label>Food</label>
                            <input class="form-control" name="title">
                        </div>
                        <div class="form-group">
                            <label>Price</label>
                            <input class="form-control" name="price">
                        </div>
                        <button type="submit" class="btn btn-default">Add</button>
                        <button type="reset" class="btn btn-default">Reset</button>
                    </form>
                </div>
                <div class="col-lg-6">
                </div>
                <!-- /.row -->
            </div>
            <!-- /#page-wrapper -->
        </div>
    </div>
    <!-- /#wrapper -->
    <!-- JavaScript -->
</body>

</html>