OnlineOrder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from OnlineOrder import settings

urlpatterns = [
    url(r'^shopmgr/', include('shopmgr.urls')),
    url(r'^mainpage/', include('mainpage.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^authorize$', views.authorize, name='authorize'),
    url(r'^jmp_register$', views.jmp_to_register, name='jmp_to_register'),
    url(r'^register_page$', views.register_page, name='register_page'),
    url(r'^registered$', views.register, name='register'),
    url(
        r'duplicated_username',
        views.handle_duplicate,
        name="duplicated_username"),
    url(r'^log_out$', views.log_out, name='log_out'),
]

mainpage/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainpage'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^complete_info$', views.complete_info, name='complete'),
    url(r'^location$', views.location, name='location'),
    url(r'^personal_center$', views.jmp_to_personal, name='personal_center'),
    url(r'^jmp_to_complete_info$', views.jmp_to_complete_info,
        name="jmp_to_complete_info"),
    url(r'^query_user_info$', views.query_user_info, name="query_user_info"),
    url(r'^check_origin_pwd$', views.check_origin_pwd, name="check_origin_pwd"),
    url(r'^change_password$', views.change_password, name="change_password"),
    url(r'^add_addr$', views.add_address, name="add_addr"),
    url(r'^get_address_count$', views.get_address_count,
        name="get_address_count"),
    url(r'^show_first_page$', views.show_first_page, name="show_first_page"),
    url(r'^del_addr$', views.del_addr, name="del_addr"),
    url(r'^conf_default_addr$', views.conf_default_addr,
        name="conf_default_addr"),
    url(r'^(?P<shop_id>[0-9]+)/jmp_to_shop_detail/$',
        views.jmp_to_shop_detail, name='jmp_to_shop_detail'),
    url(r'^(?P<shop_id>[0-9]+)/shop_detail/$',
        views.shop_detail, name='shop_detail'),
    url(r'^shoppingcar$', views.jmp_to_shoppingcar, name='shoppingcar'),
    url(r'^show_shops_orderby_sales$', views.show_shops_orderby_sales,
        name='show_shops_orderby_sales'),
    url(r'^get_merchandises$', views.get_merchandises,
        name="get_merchandises"),
    url(r'^get_spec_shopinfo$', views.get_spec_shopinfo,
        name="get_spec_shopinfo"),
    url(r'^get_my_threemonth_order$', views.get_my_threemonth_order,
        name='get_my_threemonth_order'),
    url(r'^add_to_shopcar$', views.add_to_shopcar, name='add_to_shopcar'),
    url(r'^get_cart$', views.get_cart, name='get_cart'),
    url(r'^flush_cart$', views.flush_cart, name='flush_cart'),
    url(r'^get_shop_by_keywords$', views.get_shop_by_keywords,
        name="get_shop_by_keywords"),
    url(r'^get_shopinfo_by_id$', views.get_shopinfo_by_id,
        name="get_shopinfo_by_id"),
    url(r'^get_merchan_by_id$', views.get_merchan_by_id,
        name="get_merchan_by_id"),
    url(r'^place_order$', views.place_order, name="place_order"),
    url(r'^register_shop$', views.register_shop, name='register_shop'),
    url(r'^confirm_order$', views.confirm_order, name="confirm_order"),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^cancel_spec_order$', views.cancel_sepc_order, name='cancel_spec_order'),
    url(r'^delete_food_from_order$', views.delete_food_from_order, name='delete_food_from_order'),
]

shopmgr/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopmgr'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^show_today_orders_shop$', views.show_today_orders_shop, name='show_today_orders_shop'),
    url(r'^complete_shopinfo$', views.complete_shopinfo, name='complete_shopinfo'),
    url(r'^show_personal_info$', views.show_personal_info, name='show_personal_info'),
    url(r'^add_icon$', views.add_icon, name='add_icon'),
    url(r'^show_incoming_orders$', views.show_incoming_orders, name="show_incoming_orders"),
    url(r'^show_completed_orders$',views.show_completed_orders, name="show_completed_orders"),
    url(r'^add_goods$', views.add_goods, name="add_goods"),
    url(r'^jmp_to_manage_goods$', views.jmp_to_manage_goods, name="jmp_to_manage_goods"),
    url(r'^delete_good$', views.delete_good, name="delete_good"),
    url(r'^confirm_order$', views.confirm_order, name="confirm_order"),
    url(r'^decline_order$', views.decline_order, name="decline_order"),
]

mainpage/models.py
from django.db import models
from login.models import User

# Create your models here.


class Address(models.Model):
    province = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    county = models.CharField(max_length=30)
    street = models.CharField(max_length=400)
    consignee = models.CharField(max_length=30)
    consignee_tel = models.CharField(max_length=30)
    is_default = models.BooleanField(default=False)
    postcode = models.CharField(max_length=6)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Address'

    def __str__(self):
        return self.street


class Shop(models.Model):
    shopname = models.CharField(max_length=30)
    least_price = models.IntegerField()
    deliver_fee = models.IntegerField()
    review_score = models.DecimalField(max_digits=2, decimal_places=1)
    shop_img = models.ImageField(upload_to='uploads/')
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Shop'

    def __str__(self):
        return self.shopname


class Merchandise(models.Model):
    title = models.CharField(max_length=30)
    price = models.IntegerField()
    image = models.ImageField(upload_to='goods/')
    shop_id = models.ForeignKey(Shop, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Merchandise'

    def __str__(self):
        return self.title


class SalesNum(models.Model):
    month = models.IntegerField()
    sales_num = models.IntegerField()
    merchan_id = models.ForeignKey(Merchandise, on_delete=models.CASCADE)

    class Meta:
        db_table = 'SalesNum'

    def __str__(self):
        return self.merchan_id


class Orders(models.Model):
    order_num = models.CharField(max_length=20)
    order_time = models.DateTimeField()
    total_price = models.IntegerField()
    status = models.IntegerField()  # 0 not confirmed 1 confirm 2 completed
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    shop_id = models.ForeignKey(Shop, on_delete=models.CASCADE, default=None)
    address_id = models.ForeignKey(
        Address, on_delete=models.CASCADE, default=None)

    class Meta:
        db_table = "Orders"

    def __str__(self):
        return self.order_num


class OrderDetail(models.Model):
    merchan_num = models.IntegerField()
    merchan_id = models.ForeignKey(Merchandise, on_delete=models.CASCADE)
    order_id = models.ForeignKey(Orders, on_delete=models.CASCADE)

    class Meta:
        db_table = 'OrderDetail'

    def __str__(self):
        return str(self.merchan_id) + str(self.order_id)

mainpage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from login.models import User
from .models import Address, Orders, Shop, Merchandise, OrderDetail
import json
from django.contrib.auth import authenticate, login, logout
from os import sys
from django.db.models import Count, Sum
import decimal
from django.contrib.sessions.backends.db import SessionStore
from datetime import datetime
import re
from django.utils import timezone


def index(request):
    return render(request, 'mainpage/index.html', {'user': request.user})


def complete_info(request):
    curr_user = User.objects.get(pk=request.user.id)
    try:
        province = request.POST['province']
        city = request.POST['city']
        county = request.POST['county']
        street = request.POST['street']
        consignee = request.POST['consignee']
        consignee_tel = request.POST['consignphone']
        moren = request.POST['moren']
        email = request.POST['email']
        postcode = request.POST['postcode']
        if moren == 'true':
            is_default = True
        else:
            is_default = False
        cellphone = request.POST['phone']
        curr_user.cellphone = cellphone
        curr_user.email = email
        curr_user.save()
        if province != '':
            # print(is_default)
            addr = Address(province=province, city=city, county=county, street=street,
                           consignee=consignee, consignee_tel=consignee_tel, user_id=curr_user,
                           is_default=is_default, postcode=postcode)
            addr.save()
        return HttpResponse(1)
    except:
        import traceback
        print(traceback.format_exc())
        return HttpResponse(0)


def add_address(request):
    province = request.POST['province']
    city = request.POST['city']
    county = request.POST['county']
    street = request.POST['street']
    consignee = request.POST['consignee']
    consignee_tel = request.POST['consignphone']
    is_default = request.POST['moren']
    postcode = request.POST['postcode']
    print(province)
    if is_default == '1':
        print("is default!")
        try:

            Address.objects.filter(user_id__id=request.user.id).filter(
                is_default=True).update(
                is_default=False)
        except:
            return HttpResponse(0)

    try:
        addr = Address(province=province, city=city, county=county, street=street,
                       consignee=consignee, consignee_tel=consignee_tel, user_id=request.user,
                       is_default=is_default, postcode=postcode)
        addr.save()
        return HttpResponse(1)
    except:
        return HttpResponse(0)


def location(request):
    return render(request, 'mainpage/location.html', {'user': request.user})


def jmp_to_personal(request):
    return render(request, 'mainpage/personal_center_page.html', {'user': request.user})


def jmp_to_complete_info(request):
    return render(request, 'mainpage/complete_info.html', {'user': request.user})


def query_user_info(request):
    response_data = {}
    curr_user = User.objects.get(pk=request.user.id)
    cellphone = curr_user.cellphone
    email = curr_user.email
    response_data['phone'] = cellphone
    response_data['email'] = email
    return HttpResponse(json.dumps(response_data))


def check_origin_pwd(request):
    password = request.POST['originPass']
    # print(password)
    user = authenticate(username=request.user.username, password=password)
    if user is not None:
        return HttpResponse(1)
    else:
        return HttpResponse(0)


def change_password(request):
    try:
        password = request.POST['newPass']
        user = User.objects.get(pk=request.user.id)
        user.set_password(password)
        user.save()
        # print(password)
        return HttpResponse(1)
    except:
        return HttpResponse(0)


def get_address_count(request):
    try:
        addrs = Address.objects.filter(user_id=request.user)
        addr_count = addrs.count()
        # print(addr_count)
        return HttpResponse(addr_count)
    except Address.DoesNotExist:
        return HttpResponse(0)


def show_first_page(request):
    pagenum_temp = request.POST['pagenum']
    limits_temp = request.POST['limits']
    pagenum = int(pagenum_temp)
    limits = int(limits_temp)
    start = (pagenum - 1) * limits
    addr_table = Address.objects.filter(
        user_id=request.user).order_by('-id')[start:start + limits].values()
    addr_list = list(addr_table)
    response_data = {}
    response_data['address_array'] = addr_list
    return HttpResponse(json.dumps(response_data))


def del_addr(request):
    addr_id = int(request.POST['address_id'])
    addr = Address.objects.get(pk=addr_id)
    addr.delete()
    # addr.save()
    return HttpResponse(1)


def conf_default_addr(request):
    try:
        addr_id = int(request.POST['default_addr_id'])
        # print(addr_id)
        Address.objects.filter(user_id=request.user,
                               is_default=True).update(is_default=False)
        default_user = Address.objects.get(pk=addr_id)
        default_user.is_default = True
        default_user.save()
        return HttpResponse(1)
    except:
        return HttpResponse(0)


def jmp_to_shop_detail(request, shop_id):
    return HttpResponseRedirect(reverse('mainpage:shop_detail', args=(shop_id,)))


def shop_detail(request, shop_id):
    return render(request, 'mainpage/shoper_detail.html', {'shop_id': shop_id})


def jmp_to_shoppingcar(request):
    return render(request, 'mainpage/shopping_car.html', {'user': request.user})


def decimal_default(obj):
    if isinstance(obj, decimal.Decimal):
        return float(obj)
    raise TypeError('Type not serializable')


def json_serialize(obj):
    if isinstance(obj, datetime):
        serial = obj.isoformat()
        return serial
    raise TypeError('Type not serializable')


def show_shops_orderby_sales(request):
    all_orders = Orders.objects.values(
        'shop_id_id').annotate(Count('shop_id_id'))
    # print(list(all_orders))
    all_shop_list = list(Shop.objects.order_by('id').values())
    all_shop_dict = {}
    all_shop = []
    for shop in all_shop_list:
        all_shop_dict[shop['id']] = shop
    # print(all_shop_dict)
    for order in all_orders:
        shop_id = order['shop_id_id']
        all_shop_dict[shop_id]['sales_num'] = order['shop_id_id__count']
    # print(all_shop)
    for k in list(all_shop_dict):
        all_shop.append(all_shop_dict[k])
    # print(all_shop)
    response_data = {}
    response_data['shopArray'] = all_shop
    # print(response_data)
    return HttpResponse(json.dumps(response_data, default=decimal_default))


def get_merchandises(request):
    shop_id = request.POST['shop_id']
    all_merchandises = Merchandise.objects.filter(shop_id_id=shop_id).values()
    merchandise_table = list(all_merchandises)
    response_data = {}
    response_data['foodsArray'] = merchandise_table
    return HttpResponse(json.dumps(response_data))


def get_spec_shopinfo(request):
    print(request.user.id)
    shop_id = request.POST['shop_id']
    shop = Shop.objects.get(pk=shop_id)
    user_id = shop.user_id_id
    user = User.objects.get(pk=user_id)
    addr = Address.objects.get(user_id_id=user_id)
    response_data = {}
    response_data['shopname'] = shop.shopname
    response_data['least_price'] = shop.least_price
    response_data['deliver_fee'] = shop.deliver_fee
    response_data['review_score'] = float(shop.review_score)
    response_data['shop_img'] = str(shop.shop_img)
    response_data['cellphone'] = user.cellphone
    response_data['address'] = addr.street + ', ' + addr.city
    print(response_data)
    return HttpResponse(json.dumps(response_data))


def add_to_shopcar(request):
    good_id = request.POST['food_id']
    shop_id = request.POST['shop_id']
    cart = request.session.get("cart", None)
    if not cart:
        print("Init cart")
        cart = {}
        cart[shop_id] = [good_id]
        request.session['cart'] = cart
        request.session.save()
    else:
        print("add to cart")
        if shop_id in list(cart.keys()):
            cart[shop_id].append(good_id)
        else:
            cart[shop_id] = [good_id]
        request.session.save()
    print(request.session['cart'])
    return HttpResponse(1)


def get_cart(request):
    user_id = request.user.id
    cart = request.session.get("cart", None)
    if not cart:
        return HttpResponse(0)
    print(cart)
    cart_dic = {}
    for key in cart.keys():
        temp = dict()
        for x in cart[key]:
            tmp = dict()
            tmp['cnt'] = cart[key].count(x)
            merchandise = Merchandise.objects.get(pk=x)
            tmp['price'] = merchandise.price
            tmp['food_name'] = merchandise.title
            tmp['food_img'] = str(merchandise.image)
            temp[x] = tmp
        cart_dic[key] = temp
    # cart_dic.append({key:temp})
    response_data = {}
    print(cart_dic)
    shop_info = {}
    for shop_id in cart:
        shop = Shop.objects.get(pk=shop_id)
        temp = dict()
        temp['shopname'] = shop.shopname
        temp['deliver_fee'] = shop.deliver_fee
        shop_info[shop_id] = temp
    response_data['shoppingcar_array'] = cart_dic
    response_data['shop_info'] = shop_info
    return HttpResponse(json.dumps(response_data))


def flush_cart(request):
    print("clear cart")
    request.session['cart'] = {}
    request.session.save()
    return HttpResponse(1)


def get_shop_by_keywords(request):
    print("get by keywords")
    keywords = request.POST['keyword']
    shop_set = Shop.objects.filter(shopname__contains=keywords).values()
    shop_list = list(shop_set)
    print(shop_list)
    response_data = {}
    response_data['shopArray'] = shop_list
    return HttpResponse(json.dumps(response_data, default=decimal_default))

mainpage/templates/mainpage/index.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'mainpage/css/bootstrap.css' %}" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'mainpage/js/jquery.min.js' %}"></script>
    <script src="{% static 'mainpage/js/mainpage_get_data.js' %}"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="{% static 'mainpage/css/indexstyle.css' %}" rel="stylesheet" type="text/css" />
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Food shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script>
    addEventListener("load", function() {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
    </script>
    <script src="{% static 'mainpage/js/move-top.js' %}"></script>
    <script src="{% static 'mainpage/js/easing.js' %}"></script>
    <script>
    jQuery(document).ready(function($) {
        $(".scroll").click(function(event) {
            event.preventDefault();
            $('html,body').animate({
                scrollTop: $(this.hash).offset().top
            }, 1000);
        });
    });
    </script>
</head>

<body>
    <!--header-->
    <div class="header">
        <div class="container">
            <div class="header-top-bar">
                <ul class="header-grid">
                    {% if user.username != '' %}
                    <script>
                    $(".header-grid").css("left", "70%");
                    $(".header-grid").css("top", "3%");
                    </script>
                    <li style="margin-right: 10px">
                        <div class="dropdown-top">
                            <a href="#">Welcome，{{ user.username }}</a>
                            <div class="dropdown-content-top">
                                <a href="{% url 'mainpage:personal_center' %}">Personal Center</a>
                                <a href="{% url 'login:log_out' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <a href="{% url 'mainpage:shoppingcar' %}"><img class="shopping-car" src="{% static 'mainpage/css/images/shoppingcar.png' %}">
                        </a>
                    </li>
                    {% if user.is_shop %}
                    <li><a href="{% url 'shopmgr:index' %}" style="color: #7a7a7a">Order Manage</a></li>
                    {% else %}
                    <li><a href="{% url 'mainpage:register_shop' %}">Open Restaurant</a></li>
                    {% endif %} {% else %}
                    <script>
                    $(".header-grid").css("left", "70%");
                    $(".header-grid").css("top", "3%");
                    </script>
                    <li><a href="{% url 'login:index' %}">Sign in</a></li>
                    
                    <li style="margin-right: 10px"><a href="{% url 'login:jmp_to_register' %}">Sign up</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="logo">
                <h1>
                <a href="{% url 'mainpage:index' %}">Online Order</a>
            </h1>
                <a href="{% url 'mainpage:location' %}" style="margin-left:170px;font-size: 1em;color:#000;text-decoration: none;">My Position</a>
            </div>
            <div class="banner">
                <div class="banner-in">
                    <div class="wmuSlider example1">
                        <div class="wmuSliderWrapper">
                        </div>
                    </div>
                    <!---->
                    <script src="{% static 'mainpage/js/jquery.wmuSlider.js' %}"></script>
                    <script>
                    $('.example1').wmuSlider({
                        pagination: true,
                    });
                    </script>
                    <!---->
                </div>
            </div>
            <!---->
            <div class="header-bottom">
                <div class="top-nav">
                    <ul>
                        <li class="active"><a href="#">Sales</a>
                            <label>| </label>
                        </li>
                        <li><a href="#">Rating</a>
                            <label>|</label>
                        </li>
                    </ul>
                </div>
                <script>
                getShopInfoBySalesOrComments("sales", 1);
                cur_page = 1;
                $(".top-nav ul li").click(function() {
                    if ($(this).hasClass("active") == false) {
                        $(".top-nav ul li.active").removeClass("active");
                        $(this).addClass("active");
                        console.log("选中：" + $(this).find("a").html());
                        if ($(this).find("a").html() == "Rating") {
                            // $(".price_select").get(0).selectedIndex = 0;
                            getShopInfoBySalesOrComments($(this).find("a").html(), 1);
                        }
                        cur_page = 1;
                    }

                });
                $(".price_select").change(function() {
                    $(".top-nav ul li.active").removeClass("active");
                    $(".top-nav ul li:last").addClass("active");
                    getShopInfoByPrice($(".price_select").val(), 1);
                    cur_page = 1;
                });
                </script>
                <div class="clearfix"></div>
            </div>
            <!---->
        </div>
    </div>
    <!---->
    <div class="content">
        <div class="container">
            <div class="content-grid">
                <div class="food-grid">
                    <div class="cup">
                    </div>
                    <script>
                    $(".cup").on('click', ".cup .cup-in a", function(event) {
                        event.preventDefault();
                        var shopId = $(this).attr("data-shop-id");
                        console.log("shop id:" + shopId);
                        location.href = shopId + "/jmp_to_shop_detail/";
                    });
                    </script>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="chooser-pager">
                <button class="btn btn-info  prev-pager btn-lg" style="margin-right: 10px">Previous</button>
                <button class="btn btn-info next-pager btn-lg" style="margin-left:10px">Next</button>
                <button class="btn btn-info  btn-lg" id="clear-cart" style="margin-left: 20px;">Clear Cart</button>
            </div>
            <script>
            $(".prev-pager").click(function() {
                var choosedCondition = $(".top-nav ul li.active").find("a").text();
                if (choosedCondition != "起步价筛选") {
                    getShopInfoForPrevBySalesOrComments(choosedCondition);

                } else {
                    var selectorValue = $(".price_select").val();
                    getShopInfoForPrevByLeastPrice(selectorValue);
                }


            });
            $(".next-pager").click(function() {
                var choosedCondition = $(".top-nav ul li.active").find("a").text();
                if (choosedCondition != "起步价筛选") {
                    getShopInfoForNextBySalesOrComments(choosedCondition);

                } else {
                    var selectorValue = $(".price_select").val();
                    getShopInfoForNextByLeastPrice(selectorValue);
                }

            });

            function getConditionForPagerChooser() {


            }

            $("#clear-cart").click(function() {
                // alert("clicked");
                $.get("/mainpage/flush_cart", function() {
                    alert("Clear cart successfully!");

                });
            });
            </script>
        </div>
    </div>
    <!---->
    <div class="footer">
        <div class="container">
            <div class="footer-bottom ">
                <p class="footer-grid">Copyright &copy; ZIYANG WANG &amp; MIAO GAO</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $().UItoTop({
            easingType: 'easeOutQuart'
        });

    });
    </script>
    <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
</body>

</html>

mainpage/templates/mainpage/location.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <title>Home</title>
    <link href="{% static 'mainpage/css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <link href="{% static 'mainpage/css/indexstyle.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'mainpage/js/jquery.min.js' %}" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
    #allmap {
        width: 1120px;
        height: 600px;
        overflow: hidden;
        margin: auto;
    }
    </style>
</head>

<body>
    <div class="header">
        <div class="container">
            <div class="header-top-bar">
                <ul class="header-grid">
                    {% if user.username != '' %}
                    <script type="text/javascript">
                    $(".header-grid").css("left", "70%");
                    $(".header-grid").css("top", "3%");
                    </script>
                    <li style="margin-right: 10px">
                        <div class="dropdown-top">
                            <a href="#">Welcome，{{ user.username }}</a>
                            <div class="dropdown-content-top">
                                <a href="{% url 'mainpage:personal_center' %}">Personal Center</a>
                                <a href="{% url 'login:log_out' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <a href="{% url 'mainpage:shoppingcar' %}"><img class="shopping-car" src="{% static 'mainpage/css/images/shoppingcar.png' %}">
                        </a>
                    </li>
                    {% if user.is_shop %}
                    <li><a href="{% url 'shopmgr:index' %}" style="color: #7a7a7a">Order Manage</a></li>
                    {% else %}
                    <li><a href="{% url 'mainpage:register_shop' %}">Open Restaurant</a></li>
                    {% endif %} {% else %}
                    <script type="text/javascript">
                    $(".header-grid").css("left", "70%");
                    $(".header-grid").css("top", "3%");
                    </script>
                    <li><a href="{% url 'login:index' %}">Sign in</a></li>
                    <label>|</label>
                    <li style="margin-right: 10px"><a href="{% url 'login:jmp_to_register' %}">Sign up</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="logo">
                <h1>
                <a href="{% url 'mainpage:index' %}">Online Order</a>
            </h1>
                <a href="{% url 'mainpage:location' %}" style="margin-left:170px;font-size: 1em;color:#000;text-decoration: none;">My Position</a>
            </div>
            <div class="contact-in">
                <h2>Location</h2>
                <div id="allmap">
                </div>
            </div>
            <div class="footer">
                <div class="container">
                    <div class="footer-bottom ">
                        <p class="footer-grid">Copyright &copy; ZIYANG WANG &amp; MIAO GAO</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
    var loc = { lat: -34.397, lng: 150.644 };
    var requestBody = {
        "homeMobileCountryCode": 310,
        "homeMobileNetworkCode": 410,
        "radioType": "gsm",
        "carrier": "Vodafone",
        "considerIp": "true",
        "cellTowers": [
            // See the Cell Tower Objects section below.
        ],
        "wifiAccessPoints": [
            // See the WiFi Access Point Objects section below.
        ]
    };
    // console.log(typeof requestBody);

    var map;

    function initMap() {
        $.ajax({
            type: 'POST',
            url: 'https://www.googleapis.com/geolocation/v1/geolocate?key=AIzaSyCHPr9Sea5pe5xafX5R-fPFNsUXnOOVX-0',
            data: JSON.stringify(requestBody),
            success: function(data) {
                console.log(data);
                console.log(data['location']);
                loc = data['location'];
                map = new google.maps.Map(document.getElementById('allmap'), {
                    center: loc,
                    zoom: 16
                });
            },
            contentType: "application/json",
            dataType: "json"
        });

    }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmhdRPxlmIYWS_VhIXLevV6FH8pa7JpVM&callback=initMap" async defer></script>Ï
</body>

</html>